version: '3.8'

services:
  django:
    build: .
    container_name: django_vps
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=postgres
      - DB_NAME=django_db
      - DB_USER=django_user
      - DB_PASSWORD=django_password
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge